robot_cfg:
  name: franka_gripper
  urdf_path: gen_72_b_description/urdf/GEN72_franka_side.urdf 
  dof_num: 18                                                                                                                                                                                                               

  left_arm_indices: [0, 1, 2, 3, 4, 5, 6]                                               
  right_arm_indices: [9, 10, 11, 12, 13, 14, 15]

  # 横向
  # left_arm_init: [-0.231, 0.573, -0.2131, -1.983, 0.0140, 0.4957, 0.3273] old
  # left_arm_init: [-0.17810579,-0.6379222,-0.1678573,-1.9614271,0.36395705,0.84694326,0.65826476]   //2.4039316
  # left_arm_init: [0.27377135, -0.74260074, -0.3113867 , -2.1312518,  -0.21240002,  1.006088 ,2.4039316]
  # right_arm_init: [-0.27377135, -0.74260074, 0.3113867 , -2.1312518,  0.21240002,  1.006088 ,2.4039316]

  #测试，立式
  left_arm_init: [1.477 ,-1.522 , -1.600 ,-1.885 , 0.000,  -0.337 ,0.584]
  right_arm_init: [1.816,1.484,-1.416,-1.786,-0.092,0.109,0.769]

  ee_type: "gripper"
  gripper_type: "2dof"
  left_ee: l_ace
  right_ee: r_ace

  left_ee_indices: [7, 8]
  right_ee_indices: [16, 17]

  human_hand_indices: [4, 9]
  hand_low_pass_alpha: 0.8
  wrist_low_pass_alpha: 0.5

  arm:
    dt:  1e-1
    eps: 1e-4
    damp: 1e-12
    out_lp_alpha: 0.5

  ee:
    left_ee:
      gripper_range: [0.0, 0.04]

    right_ee:
      gripper_range: [0.0, 0.04]

