
robot_cfg:
  name: franka_gripper

  is_ACE: True

  mode: normal

  pos_scale: 1.4
  roll_scale: 1.4
  pitch_scale: 1.4
  yaw_scale: 1.4

  roll_limit: [-3, 3]
  pitch_limit: [-3, 3]
  yaw_limit: [-3, 3]

  roll_offset: 20

  left_wrist:
    #怀抱式
    # left_wrist_init_rot: [
    # [0.04260536, 0.39983962, -0.91559438],
    # [-0.01126604, 0.91656052, 0.39973729],
    # [0.99902846, -0.00671582, 0.043555]]
    # # left_wrist_init_rot: [[ 0.20570036,  0.97850618, -0.01459549],
    # #                       [ 0.36716614, -0.09099295, -0.92569396],
    # #                       [-0.90712534,  0.18505661, -0.37799163]]
    # left_wrist_init_pos: [-0.67, 0.21, 0.100]
    # left_center: [-0.67, 0.21, 0.100]
    #立式
    left_wrist_init_rot: [[ 0,  0, -1], [ 1,  0,  0], [ 0,  -1,  0]]
    left_wrist_init_pos: [-0.314, 0.306, 0.24]
    left_center: [-0.314, 0.306, 0.24]
    left_radius: 0.3

  right_wrist:
    #怀抱式
    # right_wrist_init_rot: [
    # [0.00690571, 0.3584159, 0.93353648],
    # [-0.18930224, -0.91620956, 0.35316386],
    # [0.98189459, -0.17915939, 0.06152186]]
    # # right_wrist_init_rot: [
    # #   [0.07155024, 0.49736246, 0.86458727],
    # #                   [0.11556338, -0.86510504, 0.48809669],
    # #                   [0.99071978, 0.0649912, -0.11937536]]
    # right_wrist_init_pos: [0.67, 0.21, 0.100]
    # right_center: [0.67, 0.21, 0.100]
    #立式
    right_wrist_init_rot: [[ 0,  0,  -1], [ -1,  0,  0], [ 0,  1,  0]]
    right_wrist_init_pos: [0.314, 0.306, 0.24]
    right_center: [0.314, 0.306, 0.24]
    right_radius: 0.3

  left_agent:
    dynamixel_cfg:
      port: /dev/serial/by-id/usb-FTDI_USB__-__Serial_Converter_FT9HDF53-if00-port0
      urdf: left_arm/robot.urdf
      ee_link_name: ee_c
    hand_cfg:
      cam_num: 4
      hand_type: Left

  right_agent:
    dynamixel_cfg:
      port: /dev/serial/by-id/usb-FTDI_USB__-__Serial_Converter_FT9HDF61-if00-port0
      urdf: right_arm/robot.urdf
      ee_link_name: ee_c
    hand_cfg:
      cam_num: 2
      hand_type: Right




